adds: ELK stack initial configuration and Telescope Integration
humphd/telescope pull request #3
Opened 2021-02-07 17:17 UTC by raygervais

## Issue This PR Addresses

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [X] **New Feature**: Change which adds functionality
- [X] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This adds the initial integration of Telescope's logging of posts to Kibana, which can be accessed via kibana.docker.localhost. 
![image](https://user-images.githubusercontent.com/14265337/107153763-3d760b80-693d-11eb-864b-02d39c5afce6.png)
![image](https://user-images.githubusercontent.com/14265337/107153767-41a22900-693d-11eb-99a6-80ab0b00981b.png)

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-02-07 17:18 UTC, raygervais commented
Note, it appears Telescope backend / frontend aren't talking to each other. Let me see if I can fix that here prior to merge.

2021-02-08 17:10 UTC, humphd requested changes
A couple small things, then this is good to land.  Can you also rebase on my latest changes?

2021-02-08 17:10 UTC, humphd commented on env.example
> +# Microservice Development
Needed in stating/prod envs too.

2021-02-08 17:10 UTC, humphd commented on src/api/docker-compose.yaml
>      command: --api.insecure=true --providers.docker
Remove this

2021-02-08 17:23 UTC, humphd requested changes

2021-02-08 17:23 UTC, humphd commented on src/api/docker-compose.yaml
> +      - ./traefik/config/traefik.yaml:/etc/traefik/traefik.yaml"
Stray `"` at the end?

Also, are we using this file (we don't have one in the tree)?  Should we add one or do it all through labels?

2021-02-08 17:31 UTC, raygervais commented
@humphd, did you want me to add Telescope in it's half-broken state here as well? Originally I had planned on it, but may be best to do that as a separate iteration.

2021-02-08 17:31 UTC, humphd approved these changes
Looks good, can I merge?

2021-02-08 17:35 UTC, raygervais commented
Yup, this PR doesn't include the Telescope docker container anymore and moreless adds the ELK stack.

2021-02-08 17:35 UTC, humphd commented
OK, let's figure out how to connect with telescope elsewhere.  I'm not sure the right move yet, and it shouldn't block this work.

2021-02-08 17:35 UTC, merged